site_name: Furnace Docs
docs_dir: src/docs
site_dir: docs/
site_url: https://furnacetool.github.io/docs/
repo_url: https://github.com/furnacetool/furnacetool.github.io
copyright: "&copy; 2025 Furnace. All rights reserved."
theme:
  name: material
  logo: https://furnacetool.github.io/src/images/logo-nobg.png
  favicon: https://furnacetool.github.io/src/images/logo.png
  palette:
    scheme: slate
extra_css:
  - https://furnacetool.github.io/src/styles/docs.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/furnacetool
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4jvpVGpeBE